### ISSUE TITLE
Query about youtube music

### ISSUE THREAD

**Issue by souravj96** [tprelog/homeassistant-gmusic_player#11]
is there any further updates going for YouTube Music integration?

new thing came, Youtube Music.
are you planning anything to integrate it with home assistant?

**Comment by tprelog** [comment]
Sort answer ... probably not

Long answer ... I would really love to try but at this point, still not likely

This component is a hack job on @Danielhiversen [original work](https://github.com/Danielhiversen/home-assistant_config/blob/master/custom_components/switch/gmusic.py). I have spent some time trying to learn Python, and with some basic understanding and the help of Google ...  I have managed to keep this somewhat alive.

Unfortunately, I have not been successful to expand my Python skills beyond any basic levels. I have questions about things ... I don't understand enough to ask the questions, let alone the answers :disappointed:

I will continue to keep gmusic alive for as long as possible but I do not expect to attempt another custom component in the future.

**Comment by enablingpenguin** [comment]
Looks like someone is working on a [ytmusicapi](https://github.com/sigma67/ytmusicapi).

**Comment by stboch** [comment]
Home-Assistant .115 is adding a media browser and I think its a perfect opportunity to use the ytmusicapi as it will allow the library directly in HA. 
https://community.home-assistant.io/t/youtube-music-media-browser/226367

**Comment by tprelog** [comment]
Have a look at this
https://community.home-assistant.io/t/youtube-music-media-browser/226367/17

**Comment by tprelog** [comment]
This is being worked on by someone else here
https://github.com/KoljaWindeler/ytube_music_player
