### ISSUE TITLE
Deprecation warning with HA 0.110.5

### ISSUE THREAD

**Issue by sparkydave1981** [tprelog/homeassistant-gmusic_player#12]
After updating from HA 0.109.6 to HA 0.110.5 I started getting the below warning:

Log Details (WARNING)
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:938
Integration: Media Player (documentation, issues)
First occurred: 8 June 2020, 17:00:13 (1 occurrences)
Last logged: 8 June 2020, 17:00:13

MediaPlayerDevice is deprecated, modify GmusicComponent to extend MediaPlayerEntity

**Comment by tprelog** [comment]
Please try updating to the `master` branch using **Reinstall** from the integration window in HACS

![image](https://user-images.githubusercontent.com/35702532/84166989-a2dacb00-aa43-11ea-8df8-433e92d3f766.png)

![image](https://user-images.githubusercontent.com/35702532/84166629-247e2900-aa43-11ea-83d8-668e04fb9ca0.png)

**Comment by sparkydave1981** [comment]
That seems to have sorted it out, thanks!
