### ISSUE TITLE
Playlist stops after first track

### ISSUE THREAD

**Issue by OptimusGREEN** [tprelog/homeassistant-gmusic_player#13]
Hi,

I'm having an issue where if I play a playlist then it only plays the first track and never moves on to the second track.

I have the proxy set up also as per the instructions.

Any ideas?

**Comment by OptimusGREEN** [comment]
anyone?

**Comment by OptimusGREEN** [comment]
Hi,

Thanks for replying.

Yes the auto advance automation is already on. 

Any other ideas?

**Comment by tprelog** [comment]
:thinking: When you power on the gmusic_player, does the first track automatically play or do you need to start playback manually? 

Can you manually advance to the next track? 

Does the next track auto-play if you manually advance?

**Comment by OptimusGREEN** [comment]
superb!

This was an automation i was doing for playing my daughters night music and i was doing play_media or media_play rather than turn on.

this is now working as expected so closing.

thanks again.
