### ISSUE TITLE
Some helpful updates to documentation?

### ISSUE THREAD

**Issue by pmcelreavy** [tprelog/homeassistant-gmusic_player#3]
I think you should add some documentation on how to get the device_id. It's not really obvious. I happened to fall on it by chance while looking at the logs.

**Comment by rpitera** [comment]
@pmcelreavy I don't understand this either; can you elaborate on what is necessary here based on what you found?

**Comment by pmcelreavy** [comment]
@rpitera I gave up on gmusic_player since it just never worked properly for me in HomeAssistant. But, if you look at the logs, you'll see that it spits out a bunch of different IDs. There's one that is a different size (I really can't remember which, 16 characters maybe?) and I used that one. Sorry, I can't help more than that...

**Comment by rpitera** [comment]
@pmcelreavy No need for sorry, I appreciate the quick reply.  I had just discovered this by searching the initial forum thread, but I agree it should be part of the docs here and in the add on description.

**Comment by tprelog** [comment]
@pmcelreavy @rpitera 

Sorry I have been slacker since I have taken the summer off. Now I'm slowly starting to get back to this.

I'll try to update the docs over this weekend. In the meantime please see this post.
https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918/15?u=troy

**Comment by pmcelreavy** [comment]
@tprelog Thanks! That is the post I try to follow, but it's huge and getting difficult to follow. I'm glad though that you haven't abandoned the project.

**Comment by tprelog** [comment]
@pmcelreavy I understand.

The link above is to a specific post inside the thread directly answering the question of `device_id`

I think it was several weeks after you created an issue that this post appeared so you would not have found this information at that time.

**Comment by rpitera** [comment]
I found what I was looking for, but since I use split configs I had to do my install more manually and forego the packages - got it working somewhat and at the moment still testing....
