### ISSUE TITLE
Automatically skips to next song randomly

### ISSUE THREAD

**Issue by redskinwashingtons** [tprelog/homeassistant-gmusic_player#6]
While playing, sometimes the player skips to the next song before the current one is ended. I've tried timing but can't find a pattern, and it doesn't do it every time. I'd say this happens once every 2 or 3 songs. Is this a (known) bug or is there something else interfering?

**Comment by miikkajo** [comment]
seems to be some kind of url expire problem,
for me it worked fine for whole summer but started skippin few weeks ago.

using gmusic proxy should fix this problem as it caches stream but cannot say anythin sure yet.

i created hass addon for gmusic proxy but i'm still working on it:
https://github.com/miikkajo/hassio_addons

**Comment by tprelog** [comment]
What @miikkajo said. A few people including myself have started having this problem since around the end of summer. For now, you can use [gmusicproxy ](https://github.com/gmusicproxy/gmusicproxy#gmusicproxy--google-play-music-proxy) as a workaround until this is fixed more correctly. If set gmusic_player can stream from your local gmusicproxy server. Enable this by entering the proxy url in `gmusic_config.yaml`

**Example url**

```
    gmusicproxy: "http://192.168.1.100:9999"
```

In the future, I think gmusic_player should be able to cache an entire song on its own but at this point I don't know how to do that.

**Comment by miikkajo** [comment]
yep, finally get around of testing gmusicproxy addon docker, no skipping. working great.
i'll kind of like this idea, gmusic proxy is handling all authentications and stuff
and player can focus on playing... also addon is better place prosessing stuff anyway

**Comment by pmcelreavy** [comment]
Yeah, that's what I'm going to be testing too. That way, I just spin up a container per Google Play account. That part works. I now need to connect with gmusic player.

**Comment by LeonardoFalcon** [comment]
Is the gmusicproxy work around only possible with docker installations of HA/Hassio.io? I am running Hass.io on Raspberry Pi.

**Comment by raptr55** [comment]
> Is the gmusicproxy work around only possible with docker installations of HA/Hassio.io? I am running Hass.io on Raspberry Pi.

gmusic_config.yaml the gmusicproxy ( same ip shown in the Hass.io: add-on details :
{
  "url": "http://192.168.1.2",
  "port": "9999"
}
) nothing is reproduced. if i omit the gmusicproxy everythings ok exept the skipping track issue

**Comment by tprelog** [comment]
@LeonardoFalcon 
 gmusicproxy can run anywhere on your local network as long as HA can access it. I running gmusicproxy in a virtualenv. I don't use any docker or Hass.io so I sorry I can't be much of a help to answer those questions.

 @raptr55 
 I do remember seeing [this in the forum thread](https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918/51?u=troy) but I think it's just docker, not directly Hass.io.
> I did have to use the IP of my host instead of localhost to get it connected, but it is working great.

Are you using @miikkajo [gmusicproxy addon](https://github.com/miikkajo/hassio_addons/tree/master/gmusicproxy)? Maybe I misunderstand and you copied add-on details? But just in case, entry in `gmusic_config.yaml` should be like this
```
    gmusicproxy: http://192.168.1.2:9999
```

**Comment by raptr55** [comment]
> @LeonardoFalcon
> gmusicproxy can run anywhere on your local network as long as HA can access it. I running gmusicproxy in a virtualenv. I don't use any docker or Hass.io so I sorry I can't be much of a help to answer those questions.
> 
> @raptr55
> I do remember seeing [this in the forum thread](https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918/51?u=troy) but I think it's just docker, not directly Hass.io.
> 
> > I did have to use the IP of my host instead of localhost to get it connected, but it is working great.
> 
> Are you using @miikkajo [gmusicproxy addon](https://github.com/miikkajo/hassio_addons/tree/master/gmusicproxy)? Maybe I misunderstand and you copied add-on details? But just in case, entry in `gmusic_config.yaml` should be like this
> 
> ```
>     gmusicproxy: http://192.168.1.2:9999
> ```

in order to get it work i've put the local ip address of my rasp+home assistant! or in a more easiest way: the ip get it from the "OPEN WEB UI" button on the add-on page
