### ISSUE TITLE
Unable to turn on Google Music Player

### ISSUE THREAD

**Issue by Padrone56** [tprelog/homeassistant-gmusic_player#8]
Good day! 

Disclaimer to start with: I'm pretty new to Home Assistant, but I do believe I have the basics down.

Now to my issue:

- I installed the extension/plugin/component using HACS
- Completed all of the setup and config
- My account is successfully connected, as it loads my playlists.
- I'm using Kodi as my media center, and I have confirmed that it will stream mp3 files.

You can see all of this below:
![image](https://user-images.githubusercontent.com/21170415/71478163-d65bcd00-27f6-11ea-9f00-0d9ced689356.png)

The player just wont turn on when I click the button. I'm not sure how to start playback otherwise.
![image](https://user-images.githubusercontent.com/21170415/71478190-f9867c80-27f6-11ea-9c6e-fec7ef61471b.png)

I did check the logs, and there are no errors present.

I would appreciate it if anyone could help me with this.

**Comment by pacmora** [comment]
Configuring user interface, click on the top-right button and click on "Entities not used" or similar (My UI is in Spanish). You will see all the entities that are not displayed.

**Comment by Padrone56** [comment]
I actually found the issue, playing from the player to Kodi, it seems that the songs are only added to the playlist, but never actually start. So when I finish playing something, the second it finishes, the sent music will start playing.

**Comment by Padrone56** [comment]
But I've given up on the player, so I'll close this.
